sudo: false
language: python

matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6

addons:
  apt:
    packages:
    - libboost-python-dev
    - libboost-thread-dev
    - libbluetooth-dev
    - libglib2.0-dev
    - python3-dbus
install:
- pip install codecov gattlib pygatt gatt
script: coverage run --source=. `which nosetests` tests --nocapture
after_success:
- coverage report -m
- codecov
