sudo: false
env:
- DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket

language: python
virtualenv:
  system_site_packages: true

matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.4

addons:
  apt:
    packages:
    - libboost-python-dev
    - libboost-thread-dev
    - libbluetooth-dev

    - libglib2.0-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libgirepository-1.0-1

    - python-dbus
    - python-gi
    - python3-dbus
    - python3-gi
install:
- find /var/run | grep dbus
- pip install codecov gattlib pygatt gatt pexpect


script: coverage run --source=. `which nosetests` tests --nocapture

after_success:
- coverage report -m
- codecov
